### ISSUE TITLE
There is a way to control the audio playback?

### ISSUE THREAD

**Issue by KalebPortillo** [mybigday/react-native-media-player#3]
Thanks for this awesome package!
I want to make a Audio Player, so I wonder if with this package there is any way to control the soundtrack, like pausing, forwarding, trackbar of the audio, etc...
Cheers!

**Comment by pepper** [comment]
Hi, thanks you like this project

This media player is made for show, wedding or some performance, so you can see there is no deep action for all media, and currently those are not in our short-term plan. If you only want audio playback I think there is some great project maybe can help you:

[react-native-sound](https://www.npmjs.com/package/react-native-sound)
[react-native-audioplayer](https://www.npmjs.com/package/react-native-audioplayer)
