### ISSUE TITLE
undefined is not an object (evaluating 'this.RNMediaPlayer.initialize')

### ISSUE THREAD

**Issue by magicspon** [mybigday/react-native-media-player#6]
All linked up, via `react-native link`

"react": "15.3.1",
"react-native": "0.32.0",
"react-native-fs": "^1.5.1",
"react-native-media-player": "^0.2.1"

undefined is not an object (evaluating 'this.RNMediaPlayer.initialize')
MediaPlayer
    media_player.js:33
<unknown>
    index.js:11
loadModuleImplementation
    require.js:122
guardedLoadModule
    require.js:65
_require
    require.js:49
<unknown>
    index.android.js:5
loadModuleImplementation
    require.js:122
guardedLoadModule
    require.js:58
_require
    require.js:49
global code
    require-0.js:1

**Comment by jhen0409** [comment]
Looks like it is not correctly link, expected `NativeModules.RNMediaPlayer` is not undefined. Could you provide your linked package list of `MainApplication`?

**Comment by pepper** [comment]
No more info
